defaults:
  - config: default
  - optimization_config: default
  - data_config: default
  - metrics_config: default

experiment_dir: ???
do_overwrite: False

log_every_n_steps: 50
num_dataloader_workers: ???

do_detect_anomaly: False
do_final_validation_on_metrics: True
