defaults:
  - pretrain_config
  - _self_

do_overwrite: false

# misc
seed: 1
experiment_dir: models/${now:%Y-%m-%d_%H-%M-%S}  # why do we need this? save everything to save_dir

model:
  do_use_learnable_sinusoidal_ATE: false
  do_split_embeddings: false
  categorical_embedding_dim: null
  numerical_embedding_dim: null
  static_embedding_mode: sum_all
  static_embedding_weight: 0.5
  dynamic_embedding_weight: 0.5
  categorical_embedding_weight: 0.4
  numerical_embedding_weight: 0.5
  do_normalize_by_measurement_index: false
  structured_event_processing_mode: conditionally_independent
  num_hidden_layers: 12
  seq_attention_types:
  - global
  TTE_generation_layer_type: log_normal_mixture
  TTE_lognormal_generation_num_components: 8
  head_dim: 64
  hidden_size: 768
  num_attention_heads: 12
  attention_dropout: 0.1
  input_dropout: 0.1
  resid_dropout: 0.0
  intermediate_size: 3072

training:
  max_epochs: 100
  batch_size: 64
  validation_batch_size: 64
  patience: 5
  gradient_accumulation: null
  num_dataloader_workers: 8
  use_bfloat16: true

  optimizer:
    type: AdamW
    weight_decay: 0.1
  scheduler:
    type: polynomial_decay
    init_lr: 1e-3
    lr_frac_warmup_steps: 0.05
    end_lr_frac_of_init_lr: 0.1
    end_lr: null
    lr_decay_power: 1.0

  accelerator: auto
  devices: auto
  detect_anomaly: false
  log_every_n_steps: 1
  wandb_logger_kwargs:
    project: MIMIC_FMs_public
    name: null  # default to wand names


data:
  save_dir: /mnt/shared_home/vlialin/documents/EventStreamGPT/data/MIMIC_IV/ESD_06-13-23_150GB_10cpu-1
  max_seq_len: 190
  min_seq_len: 4
  train_subset_size: FULL
  train_subset_seed: null
  task_df_name: null
  do_include_subsequence_indices: false
  do_include_subject_id: false
  do_include_start_time_min: false

evaluation:
  do_final_validation_on_metrics: true

  pretraining_metrics_config:
    n_auc_thresholds: 50
    do_skip_all_metrics: false
    do_validate_args: false
    include_metrics:
      train:
        LOSS_PARTS: true

  final_validation_metrics_config:
    n_auc_thresholds: 25
    do_skip_all_metrics: false
    do_validate_args: false  # what does this one do? maybe remove it?
    include_metrics:
      TUNING:
        LOSS_PARTS: true  # remove, always report?
        TTE:
          MSE: true  # remove, always report?
          MSLE: true  # remove, always report?
        CLASSIFICATION:
          AUROC:
          - WEIGHTED
          ACCURACY: true  # remove, always report?
        REGRESSION:
          MSE: true  # remove, always report?
      HELD_OUT:
        LOSS_PARTS: true  # remove, always report?
        TTE:
          MSE: true  # remove, always report?
          MSLE: true  # remove, always report?
        CLASSIFICATION:
          AUROC:
          - WEIGHTED
          ACCURACY: true  # remove, make true always
        REGRESSION:
          MSE: true  # remove, make true always
